# Generated by Django 5.2.8 on 2025-12-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_adbanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='study_notes',
        ),
        migrations.AddField(
            model_name='chapter',
            name='study_notes',
            field=models.TextField(blank=True, help_text='Markdown/HTML content'),
        ),
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.CharField(default='Main', help_text="e.g. 'Paper 1', 'Technical', 'General Studies'", max_length=100),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='bg_gradient_from',
            field=models.CharField(default='blue-600', max_length=50),
        ),
        migrations.AlterField(
            model_name='adbanner',
            name='bg_gradient_to',
            field=models.CharField(default='purple-600', max_length=50),
        ),
    ]
