# Generated by Django 5.2.8 on 2025-12-13 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_topic_study_notes_chapter_study_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='chapter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz', to='exams.chapter'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='topic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_legacy', to='exams.topic'),
        ),
    ]
