# Generated by Django 5.2.8 on 2025-12-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_chapter_alter_exam_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='', help_text='Explanation for the correct answer'),
        ),
    ]
